### ISSUE TITLE
Template_Default problem - variables not set

### ISSUE THREAD

**Issue by cambiata** [beautiful/view#1]
Hi Luke! Thank you for sharing - this looks great!

The mustache template (as included in your example) seems to work perfectly well.
I'm having problem with the Template_Default behaviour though. Shouldn't the temlate types work transparently so that one template type could be replaced by another? 

I'm trying the following:
1. Changing the examples/application/classes/view.php so to work on the Template_Default instead of Template_Mustache:
   protected $_default_template = 'Template_Default';
2. Adding a examples/application/views/example.php template file.
   This works fine until I try to get the a value from the View_Example view model.

The following example.php template...

```
<b>Example</b>
<?php
echo $content;
```

...causes this error:
ErrorException [ Notice ]: Undefined variable: content

Shouldn't the $content variable be set by the model, just the way it works when using Template_Mustache?

**Comment by lukemorton** [comment]
Sorry about missing this ticket for some time ^__^

That is a problem you have described here. Only the properties of the object ViewModel will be exposed into the PHP template and not the methods. For example:

```
class View_Example extends ViewModel {

    public $content = 'My content';

}
```

In your template the $content variable would be available.

However things could be done to expose public methods, but most likely not via variables.

I could pass `$vm`, which would represent the `ViewModel` class which you could call `$vm->content()` against. As you are probably aware this is not how `View` current works.

Do you have a particular opinion on the matter?

**Comment by lukemorton** [comment]
The latest version of Beautiful View will pass in the `ViewModel` as the variable `$view`. You then have to call your public methods against that variable.
