### ISSUE TITLE
Late static binding in Template ?

### ISSUE THREAD

**Issue by ccazette** [beautiful/view#3]
I am a bit confused here as I don't get how the code can work as presently written...

In Template Class, the path() method is supposed (I guess) to use Template_Mustache or Template_PHP static $ext or $dir to generate the path. You can't access Template_Mustache::$ext from Template using self as this is presently the case : http://php.net/manual/fr/language.oop5.late-static-bindings.php

The only options I see are to use static::$ext and static::$dir or to make these properties non-static since path runs in the object context anyway...

As written now, I can't load any Mustache template since the extension self::$ext is always equal to NULL, as defined in Template.

**Comment by lukemorton** [comment]
https://github.com/beautiful/view/blob/develop/classes/beautiful/template.php#L62

^^
I'm pretty sure that code is using the `static` keyword. Or did I misunderstand?

**Comment by lukemorton** [comment]
You may have downloaded an old tag. I've just released a new tag version v0.3, but TBH I would recommend you follow the develop branch as that's where most the action happens since this is a new module.

**Comment by ccazette** [comment]
Hmm, you're right, I was struggling with an older version... Not sure how that happened...
